import { EMainStat, EOffhandType, EWeaponType } from '../types/items';
import { ERole } from '../types/roles';
import { ECharacterClass, ECharacterSpecName, TCharacterSpec } from '../types/spec';

export const ALL_SPECS: Record<ECharacterSpecName, TCharacterSpec> = {
  [ECharacterSpecName.PROT_W]: {
    characterSpecName: ECharacterSpecName.PROT_W,
    characterClass: ECharacterClass.WARRIOR,
    role: ERole.TANK,
    mainStat: EMainStat.STR,
    weaponTypes: [EWeaponType.SWORD1H, EWeaponType.AXE1H, EWeaponType.MACE1H],
    offhandTypes: [EOffhandType.SHIELD],
  },
  [ECharacterSpecName.FURY]: {
    characterSpecName: ECharacterSpecName.FURY,
    characterClass: ECharacterClass.WARRIOR,
    role: ERole.DPS_MELEE,
    mainStat: EMainStat.STR,
    weaponTypes: [
      EWeaponType.AXE1H,
      EWeaponType.AXE2H,
      EWeaponType.SWORD1H,
      EWeaponType.SWORD2H,
      EWeaponType.MACE1H,
      EWeaponType.MACE2H,
    ],
  },
  [ECharacterSpecName.ARMS]: {
    characterSpecName: ECharacterSpecName.ARMS,
    characterClass: ECharacterClass.WARRIOR,
    role: ERole.DPS_MELEE,
    mainStat: EMainStat.STR,
    weaponTypes: [EWeaponType.SWORD2H, EWeaponType.AXE2H, EWeaponType.MACE2H],
  },
  [ECharacterSpecName.PROT_P]: {
    characterSpecName: ECharacterSpecName.PROT_P,
    characterClass: ECharacterClass.PALADIN,
    role: ERole.TANK,
    mainStat: EMainStat.STR,
    weaponTypes: [EWeaponType.MACE1H, EWeaponType.SWORD1H],
    offhandTypes: [EOffhandType.SHIELD],
  },
  [ECharacterSpecName.HOLY_PALADIN]: {
    characterSpecName: ECharacterSpecName.HOLY_PALADIN,
    characterClass: ECharacterClass.PALADIN,
    role: ERole.HEALER,
    mainStat: EMainStat.INT,
    weaponTypes: [EWeaponType.MACE1H, EWeaponType.SWORD1H],
    offhandTypes: [EOffhandType.SHIELD],
  },
  [ECharacterSpecName.RETRI]: {
    characterSpecName: ECharacterSpecName.RETRI,
    characterClass: ECharacterClass.PALADIN,
    role: ERole.DPS_MELEE,
    mainStat: EMainStat.STR,
    weaponTypes: [EWeaponType.AXE2H, EWeaponType.MACE2H, EWeaponType.SWORD2H],
  },
  [ECharacterSpecName.BM]: {
    characterSpecName: ECharacterSpecName.BM,
    characterClass: ECharacterClass.HUNTER,
    role: ERole.DPS_RANGED,
    mainStat: EMainStat.AGI,
    weaponTypes: [EWeaponType.BOW, EWeaponType.CROSSBOW, EWeaponType.GUN],
  },
  [ECharacterSpecName.MM]: {
    characterSpecName: ECharacterSpecName.MM,
    characterClass: ECharacterClass.HUNTER,
    role: ERole.DPS_RANGED,
    mainStat: EMainStat.AGI,
    weaponTypes: [EWeaponType.BOW, EWeaponType.CROSSBOW, EWeaponType.GUN],
  },
  [ECharacterSpecName.SURVI]: {
    characterSpecName: ECharacterSpecName.SURVI,
    characterClass: ECharacterClass.HUNTER,
    role: ERole.DPS_MELEE,
    mainStat: EMainStat.AGI,
    weaponTypes: [EWeaponType.POLEARM],
  },
  [ECharacterSpecName.ASSA]: {
    characterSpecName: ECharacterSpecName.ASSA,
    characterClass: ECharacterClass.ROGUE,
    role: ERole.DPS_MELEE,
    mainStat: EMainStat.AGI,
    weaponTypes: [EWeaponType.DAGGER],
  },
  [ECharacterSpecName.OUTLAW]: {
    characterSpecName: ECharacterSpecName.OUTLAW,
    characterClass: ECharacterClass.ROGUE,
    role: ERole.DPS_MELEE,
    mainStat: EMainStat.AGI,
    weaponTypes: [EWeaponType.SWORD1H, EWeaponType.MACE1H, EWeaponType.DAGGER],
  },
  [ECharacterSpecName.SUB]: {
    characterSpecName: ECharacterSpecName.SUB,
    characterClass: ECharacterClass.ROGUE,
    role: ERole.DPS_MELEE,
    mainStat: EMainStat.AGI,
    weaponTypes: [EWeaponType.DAGGER],
  },
  [ECharacterSpecName.HOLY_PRIEST]: {
    characterSpecName: ECharacterSpecName.HOLY_PRIEST,
    characterClass: ECharacterClass.PRIEST,
    role: ERole.HEALER,
    mainStat: EMainStat.INT,
    weaponTypes: [EWeaponType.MACE1H, EWeaponType.DAGGER, EWeaponType.WAND],
    offhandTypes: [EOffhandType.OFFHAND],
  },
  [ECharacterSpecName.DISCI]: {
    characterSpecName: ECharacterSpecName.DISCI,
    characterClass: ECharacterClass.PRIEST,
    role: ERole.HEALER,
    mainStat: EMainStat.INT,
    weaponTypes: [EWeaponType.MACE1H, EWeaponType.DAGGER, EWeaponType.WAND],
    offhandTypes: [EOffhandType.OFFHAND],
  },
  [ECharacterSpecName.SHADOW]: {
    characterSpecName: ECharacterSpecName.SHADOW,
    characterClass: ECharacterClass.PRIEST,
    role: ERole.DPS_RANGED,
    mainStat: EMainStat.INT,
    weaponTypes: [EWeaponType.MACE1H, EWeaponType.DAGGER, EWeaponType.WAND],
    offhandTypes: [EOffhandType.OFFHAND],
  },
  [ECharacterSpecName.UNHOLY]: {
    characterSpecName: ECharacterSpecName.UNHOLY,
    characterClass: ECharacterClass.DEATH_KNIGHT,
    role: ERole.DPS_MELEE,
    mainStat: EMainStat.STR,
    weaponTypes: [EWeaponType.AXE1H, EWeaponType.MACE1H, EWeaponType.SWORD1H],
  },
  [ECharacterSpecName.BLOOD]: {
    characterSpecName: ECharacterSpecName.BLOOD,
    characterClass: ECharacterClass.DEATH_KNIGHT,
    role: ERole.TANK,
    mainStat: EMainStat.STR,
    weaponTypes: [EWeaponType.AXE1H, EWeaponType.MACE1H, EWeaponType.SWORD1H],
  },
  [ECharacterSpecName.FROST_DK]: {
    characterSpecName: ECharacterSpecName.FROST_DK,
    characterClass: ECharacterClass.DEATH_KNIGHT,
    role: ERole.DPS_MELEE,
    mainStat: EMainStat.STR,
    weaponTypes: [EWeaponType.AXE1H, EWeaponType.SWORD1H, EWeaponType.AXE2H, EWeaponType.SWORD2H],
  },
  [ECharacterSpecName.RESTO_S]: {
    characterSpecName: ECharacterSpecName.RESTO_S,
    characterClass: ECharacterClass.SHAMAN,
    role: ERole.HEALER,
    mainStat: EMainStat.INT,
    weaponTypes: [EWeaponType.MACE1H, EWeaponType.STAFF, EWeaponType.DAGGER],
    offhandTypes: [EOffhandType.OFFHAND, EOffhandType.SHIELD],
  },
  [ECharacterSpecName.ELE]: {
    characterSpecName: ECharacterSpecName.ELE,
    characterClass: ECharacterClass.SHAMAN,
    role: ERole.DPS_RANGED,
    mainStat: EMainStat.INT,
    weaponTypes: [EWeaponType.MACE1H, EWeaponType.STAFF, EWeaponType.DAGGER],
    offhandTypes: [EOffhandType.OFFHAND, EOffhandType.SHIELD],
  },
  [ECharacterSpecName.ENCH]: {
    characterSpecName: ECharacterSpecName.ENCH,
    characterClass: ECharacterClass.SHAMAN,
    role: ERole.DPS_MELEE,
    mainStat: EMainStat.AGI,
    weaponTypes: [EWeaponType.MACE1H, EWeaponType.AXE1H, EWeaponType.SWORD1H],
  },
  [ECharacterSpecName.FROST_M]: {
    characterSpecName: ECharacterSpecName.FROST_M,
    characterClass: ECharacterClass.MAGE,
    role: ERole.DPS_RANGED,
    mainStat: EMainStat.INT,
    weaponTypes: [EWeaponType.STAFF, EWeaponType.DAGGER],
    offhandTypes: [EOffhandType.OFFHAND],
  },
  [ECharacterSpecName.FIRE]: {
    characterSpecName: ECharacterSpecName.FIRE,
    characterClass: ECharacterClass.MAGE,
    role: ERole.DPS_RANGED,
    mainStat: EMainStat.INT,
    weaponTypes: [EWeaponType.STAFF, EWeaponType.DAGGER],
    offhandTypes: [EOffhandType.OFFHAND],
  },
  [ECharacterSpecName.ARCANE]: {
    characterSpecName: ECharacterSpecName.ARCANE,
    characterClass: ECharacterClass.MAGE,
    role: ERole.DPS_RANGED,
    mainStat: EMainStat.INT,
    weaponTypes: [EWeaponType.STAFF, EWeaponType.DAGGER],
    offhandTypes: [EOffhandType.OFFHAND],
  },
  [ECharacterSpecName.DESTRO]: {
    characterSpecName: ECharacterSpecName.DESTRO,
    characterClass: ECharacterClass.WARLOCK,
    role: ERole.DPS_RANGED,
    mainStat: EMainStat.INT,
    weaponTypes: [EWeaponType.STAFF, EWeaponType.DAGGER],
    offhandTypes: [EOffhandType.OFFHAND],
  },
  [ECharacterSpecName.DEMO]: {
    characterSpecName: ECharacterSpecName.DEMO,
    characterClass: ECharacterClass.WARLOCK,
    role: ERole.DPS_RANGED,
    mainStat: EMainStat.INT,
    weaponTypes: [EWeaponType.STAFF, EWeaponType.DAGGER],
    offhandTypes: [EOffhandType.OFFHAND],
  },
  [ECharacterSpecName.AFFLI]: {
    characterSpecName: ECharacterSpecName.AFFLI,
    characterClass: ECharacterClass.WARLOCK,
    role: ERole.DPS_RANGED,
    mainStat: EMainStat.INT,
    weaponTypes: [EWeaponType.STAFF, EWeaponType.DAGGER],
    offhandTypes: [EOffhandType.OFFHAND],
  },
  [ECharacterSpecName.MIST]: {
    characterSpecName: ECharacterSpecName.MIST,
    characterClass: ECharacterClass.MONK,
    role: ERole.HEALER,
    mainStat: EMainStat.INT,
    weaponTypes: [EWeaponType.STAFF, EWeaponType.POLEARM],
  },
  [ECharacterSpecName.WW]: {
    characterSpecName: ECharacterSpecName.WW,
    characterClass: ECharacterClass.MONK,
    role: ERole.DPS_MELEE,
    mainStat: EMainStat.AGI,
    weaponTypes: [EWeaponType.STAFF, EWeaponType.POLEARM],
  },
  [ECharacterSpecName.BREW]: {
    characterSpecName: ECharacterSpecName.BREW,
    characterClass: ECharacterClass.MONK,
    role: ERole.TANK,
    mainStat: EMainStat.AGI,
    weaponTypes: [EWeaponType.STAFF, EWeaponType.POLEARM],
  },
  [ECharacterSpecName.RESTO_D]: {
    characterSpecName: ECharacterSpecName.RESTO_D,
    characterClass: ECharacterClass.DRUID,
    role: ERole.HEALER,
    mainStat: EMainStat.INT,
    weaponTypes: [EWeaponType.STAFF, EWeaponType.MACE1H, EWeaponType.DAGGER],
  },
  [ECharacterSpecName.FERAL]: {
    characterSpecName: ECharacterSpecName.FERAL,
    characterClass: ECharacterClass.DRUID,
    role: ERole.DPS_MELEE,
    mainStat: EMainStat.AGI,
    weaponTypes: [EWeaponType.POLEARM, EWeaponType.FIST],
  },
  [ECharacterSpecName.BALANCE]: {
    characterSpecName: ECharacterSpecName.BALANCE,
    characterClass: ECharacterClass.DRUID,
    role: ERole.DPS_RANGED,
    mainStat: EMainStat.INT,
    weaponTypes: [EWeaponType.STAFF, EWeaponType.MACE1H, EWeaponType.DAGGER],
  },
  [ECharacterSpecName.GUARDIAN]: {
    characterSpecName: ECharacterSpecName.GUARDIAN,
    characterClass: ECharacterClass.DRUID,
    role: ERole.TANK,
    mainStat: EMainStat.AGI,
    weaponTypes: [EWeaponType.POLEARM, EWeaponType.FIST],
  },
  [ECharacterSpecName.VENG]: {
    characterSpecName: ECharacterSpecName.VENG,
    characterClass: ECharacterClass.DEMON_HUNTER,
    role: ERole.TANK,
    mainStat: EMainStat.AGI,
    weaponTypes: [EWeaponType.WARGLAIVE],
  },
  [ECharacterSpecName.HAVOC]: {
    characterSpecName: ECharacterSpecName.HAVOC,
    characterClass: ECharacterClass.DEMON_HUNTER,
    role: ERole.DPS_MELEE,
    mainStat: EMainStat.AGI,
    weaponTypes: [EWeaponType.WARGLAIVE],
  },
  [ECharacterSpecName.AUG]: {
    characterSpecName: ECharacterSpecName.AUG,
    characterClass: ECharacterClass.EVOKER,
    role: ERole.DPS_RANGED,
    mainStat: EMainStat.INT,
    weaponTypes: [EWeaponType.STAFF],
  },
  [ECharacterSpecName.DEVA]: {
    characterSpecName: ECharacterSpecName.DEVA,
    characterClass: ECharacterClass.EVOKER,
    role: ERole.DPS_RANGED,
    mainStat: EMainStat.INT,
    weaponTypes: [EWeaponType.STAFF],
  },
  [ECharacterSpecName.PRESERV]: {
    characterSpecName: ECharacterSpecName.PRESERV,
    characterClass: ECharacterClass.EVOKER,
    role: ERole.HEALER,
    mainStat: EMainStat.INT,
    weaponTypes: [EWeaponType.STAFF],
  },
};
