import {
  EItemSlot,
  EMainStat,
  EOffhandType,
  ESecondaryStat,
  EWeaponType,
  TWowItem,
} from '../types/items';
import { EDungeon, ERaid, ERaidBoss } from '../types/lootSources';

export const MANUAL_ITEMS: Array<TWowItem> = [
  {
    name: "Geezle's Coercive Volt-ohmmeter",
    itemId: 234493,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.VERS],
    specialEffect: null,
    lootSource: EDungeon.FLOOD,
    imgId: 'inv_knife_1h_outdoorundermine_c_01_purple',
    weaponType: EWeaponType.DAGGER,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Sonic Ka-BOOM!-erang',
    itemId: 234491,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.HASTE],
    specialEffect: null,
    lootSource: EDungeon.FLOOD,
    imgId: 'inv_glaive_1h_outdoorundermine_c_01',
    weaponType: EWeaponType.WARGLAIVE,
    mainStats: [EMainStat.AGI],
  },
  {
    name: "Keeza's 'B.' B.B.B.F.G",
    itemId: 234492,
    slot: EItemSlot.RANGED,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.HASTE],
    specialEffect: null,
    lootSource: EDungeon.FLOOD,
    imgId: 'inv_firearm_2h_outdoorundermine_c_01',
    weaponType: EWeaponType.GUN,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Hand of Beledar',
    itemId: 221122,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.PSF,
    imgId: 'inv_mace_1h_earthendungeon_c_01',
    weaponType: EWeaponType.MACE1H,
    mainStats: [EMainStat.INT],
  },
  {
    name: "Starforged Seraph's Mace",
    itemId: 221128,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.VERS],
    specialEffect: null,
    lootSource: EDungeon.PSF,
    imgId: 'inv_mace_1h_earthendungeon_c_01',
    weaponType: EWeaponType.MACE1H,
    mainStats: [EMainStat.AGI],
  },
  {
    name: "Stoneguardian's Morningstar",
    itemId: 178834,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.HOA,
    imgId: 'inv_mace_1h_bastionquest_b_02',
    weaponType: EWeaponType.MACE1H,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Blade of Grievous Harm',
    itemId: 185824,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.HASTE],
    specialEffect: null,
    lootSource: EDungeon.STREETS,
    imgId: 'inv_sword_1h_broker2boss_d_01_blue',
    weaponType: EWeaponType.SWORD1H,
    mainStats: [EMainStat.STR],
  },
  {
    name: "Interrogator's Flensing Blade",
    itemId: 185780,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.STREETS,
    imgId: 'inv_sword_1h_broker2boss_d_01_blue',
    weaponType: EWeaponType.SWORD1H,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Fang of Alcruux',
    itemId: 185777,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.STREETS,
    imgId: 'inv_knife_1h_broker_c_01',
    weaponType: EWeaponType.DAGGER,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Gluttonous Rondel',
    itemId: 185821,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.VERS],
    specialEffect: null,
    lootSource: EDungeon.STREETS,
    imgId: 'inv_knife_1h_broker_c_01',
    weaponType: EWeaponType.DAGGER,
    mainStats: [EMainStat.INT],
  },
  {
    name: 'Yasahm the Riftbreaker',
    itemId: 185783,
    slot: EItemSlot.RANGED,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.VERS],
    specialEffect:
      'Equip: Your damaging critical strikes grant you a stack of Preternatural Charge. When you reach 5 stacks of Preternatural Charge, your next critical strike will consume all stacks to tear open a rift near your target, inflicting 29 Arcane damage.',
    lootSource: EDungeon.STREETS,
    imgId: 'inv_crossbow_2h_broker_c_01',
    weaponType: EWeaponType.CROSSBOW,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Acoustically Alluring Censer',
    itemId: 185812,
    slot: EItemSlot.OFFHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.VERS],
    specialEffect: null,
    lootSource: EDungeon.STREETS,
    imgId: 'inv_offhand_1h_broker_c_01',
    offhandType: EOffhandType.OFFHAND,
    mainStats: [EMainStat.INT],
  },
  {
    name: 'First Fist of the So Cartel',
    itemId: 185778,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.HASTE],
    specialEffect: null,
    lootSource: EDungeon.STREETS,
    imgId: 'inv_hand_1h_brokerassassin_c_01',
    weaponType: EWeaponType.FIST,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Fatebreaker, Destroyer of Futures',
    itemId: 185823,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.VERS, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.GAMBIT,
    imgId: 'inv_mace_1h_broker_c_01',
    weaponType: EWeaponType.MACE1H,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Timetwister Tulwar',
    itemId: 185841,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.VERS, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.GAMBIT,
    imgId: 'inv_sword_1h_broker_c_01',
    weaponType: EWeaponType.SWORD1H,
    mainStats: [EMainStat.INT],
  },
  {
    name: "Event Horizon's Edge",
    itemId: 185819,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.GAMBIT,
    imgId: 'inv_glaive_1h_broker_c_01',
    weaponType: EWeaponType.WARGLAIVE,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Overclocked Plexhammer',
    itemId: 237736,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.VERS],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.PLEXUS,
      raid: ERaid.MFO,
    },
    imgId: 'inv_mace_1h_etherealraid_d_01',
    weaponType: EWeaponType.MACE1H,
    mainStats: [EMainStat.INT],
  },
  {
    name: 'Factory-Issue Plexhammer',
    itemId: 237813,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.PLEXUS,
      raid: ERaid.MFO,
    },
    imgId: 'inv_mace_1h_etherealraid_d_02',
    weaponType: EWeaponType.MACE1H,
    mainStats: [EMainStat.STR],
  },
  {
    name: 'Prodigious Gene Splicer',
    itemId: 237729,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.VERS, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.LOOMITHAR,
      raid: ERaid.MFO,
    },
    imgId: 'inv_knife_1h_etherealraid_d_01',
    weaponType: EWeaponType.DAGGER,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Piercing Strandbow',
    itemId: 237732,
    slot: EItemSlot.RANGED,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.LOOMITHAR,
      raid: ERaid.MFO,
    },
    imgId: 'inv_bow_1h_etherealraid_d_01',
    weaponType: EWeaponType.BOW,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Unbound Training Claws',
    itemId: 237738,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.NAAZINDHRI,
      raid: ERaid.MFO,
    },
    imgId: 'inv_hand_1h_etherealraid_d_01',
    weaponType: EWeaponType.FIST,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Iris of the Dark Beyond',
    itemId: 237724,
    slot: EItemSlot.OFFHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.HASTE],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.ARAZ,
      raid: ERaid.MFO,
    },
    imgId: 'inv_offhand_1h_etherealraid_d_01',
    offhandType: EOffhandType.OFFHAND,
    mainStats: [EMainStat.INT],
  },
  {
    name: 'Collapsing Phaseblades',
    itemId: 237727,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.SOUL_HUNTERS,
      raid: ERaid.MFO,
    },
    imgId: 'inv_glaive_1h_etherealraid_d_01',
    weaponType: EWeaponType.WARGLAIVE,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Voidglass Kris',
    itemId: 237728,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.MASTERY],
    specialEffect:
      'Equip: Your spells have a chance to conjure voidglass shards, slicing enemies for 223218 Cosmic damage or orbiting allies to absorb 594502 damage for up to 20 sec.',
    lootSource: {
      bossName: ERaidBoss.FRACTILLUS,
      raid: ERaid.MFO,
    },
    imgId: 'inv_knife_1h_etherealraid_d_02',
    weaponType: EWeaponType.DAGGER,
    mainStats: [EMainStat.INT],
  },
  {
    name: 'Lacerated Current Caster',
    itemId: 237733,
    slot: EItemSlot.RANGED,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.HASTE],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.FRACTILLUS,
      raid: ERaid.MFO,
    },
    imgId: 'inv_crossbow_2h_etherealraid_d_01',
    weaponType: EWeaponType.CROSSBOW,
    mainStats: [EMainStat.AGI],
  },
  {
    name: "Fractillus' Last Breath",
    itemId: 237742,
    slot: EItemSlot.OFFHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.FRACTILLUS,
      raid: ERaid.MFO,
    },
    imgId: 'inv_offhand_1h_etherealraid_d_02',
    offhandType: EOffhandType.OFFHAND,
    mainStats: [EMainStat.INT],
  },
  {
    name: "Voidglass Sovereign's Blade",
    itemId: 237735,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.HASTE],
    specialEffect:
      'Equip: Your spells have a chance to conjure voidglass shards, slicing enemies for 223218 Cosmic damage or orbiting allies to absorb 594502 damage for up to 20 sec.',
    lootSource: {
      bossName: ERaidBoss.NEXUS_KING,
      raid: ERaid.MFO,
    },
    imgId: 'inv_sword_1h_etherealraid_d_01',
    weaponType: EWeaponType.SWORD1H,
    mainStats: [EMainStat.INT],
  },
  {
    name: "Oath-Breaker's Recompense",
    itemId: 237734,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.HASTE],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.NEXUS_KING,
      raid: ERaid.MFO,
    },
    imgId: 'inv_axe_1h_etherealraid_d_01',
    weaponType: EWeaponType.AXE1H,
    mainStats: [EMainStat.STR],
  },
  {
    name: 'Vengeful Netherspike',
    itemId: 237740,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.NEXUS_KING,
      raid: ERaid.MFO,
    },
    imgId: 'inv_knife_1h_etherealraid_d_02',
    weaponType: EWeaponType.DAGGER,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Ergospheric Cudgel',
    itemId: 237731,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.VERS],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.DIMENSIUS,
      raid: ERaid.MFO,
    },
    imgId: 'inv_mace_1h_etherealraid_d_02',
    weaponType: EWeaponType.MACE1H,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Nathrian Reliquary',
    itemId: 246284,
    slot: EItemSlot.OFFHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.HOA,
    imgId: 'inv_offhand_1h_oribosdungeon_c_01',
    offhandType: EOffhandType.OFFHAND,
  },
  {
    name: 'Unceremonious Bloodletter',
    itemId: 221165,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.HASTE],
    specialEffect: null,
    lootSource: EDungeon.ARA,
    imgId: 'inv_knife_1h_earthendungeon_c_01',
    weaponType: EWeaponType.DAGGER,
    mainStats: [EMainStat.INT],
  },
  {
    name: 'Arachnoid Soulcleaver',
    itemId: 221150,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.ARA,
    imgId: 'inv_sword_1h_earthendungeon_c_02',
    weaponType: EWeaponType.SWORD1H,
    mainStats: [EMainStat.INT],
  },
  {
    name: "Parson's Ornamented Blade",
    itemId: 221138,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.VERS, ESecondaryStat.CRIT],
    specialEffect: null,
    lootSource: EDungeon.DAWN,
    imgId: 'inv_knife_1h_earthendungeon_c_02',
    weaponType: EWeaponType.DAGGER,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Overflowing Umbral Pail',
    itemId: 221132,
    slot: EItemSlot.OFFHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.VERS],
    specialEffect: null,
    lootSource: EDungeon.DAWN,
    imgId: 'inv_offhand_1h_earthendungeon_c_01',
    offhandType: EOffhandType.OFFHAND,
  },
  {
    name: "Shipwrecker's Bludgeon",
    itemId: 221145,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.HASTE],
    specialEffect: null,
    lootSource: EDungeon.DAWN,
    imgId: 'inv_mace_1h_earthendungeon_c_01',
    weaponType: EWeaponType.MACE1H,
    mainStats: [EMainStat.STR],
  },
  {
    name: 'Zephyrous Sail Carver',
    itemId: 221144,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.VERS],
    specialEffect: null,
    lootSource: EDungeon.DAWN,
    imgId: 'inv_sword_1h_earthendungeon_c_02',
    weaponType: EWeaponType.SWORD1H,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Recurved Hull Impaler',
    itemId: 221143,
    slot: EItemSlot.RANGED,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.DAWN,
    imgId: 'inv_crossbow_2h_earthendungeon_c_01',
    weaponType: EWeaponType.CROSSBOW,
    mainStats: [EMainStat.AGI],
  },
  {
    name: "Swarmite's Frenzied Pedicel",
    itemId: 242464,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.ECO,
    imgId: 'inv_wand_1h_outdoorethereal_c_01',
    weaponType: EWeaponType.WAND,
    mainStats: [EMainStat.INT],
  },
  {
    name: 'Mandibular Bonewhacker',
    itemId: 242470,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.VERS],
    specialEffect: null,
    lootSource: EDungeon.ECO,
    imgId: 'inv_mace_1h_outdoorethereal_c_02',
    weaponType: EWeaponType.MACE1H,
    mainStats: [EMainStat.STR],
  },
  {
    name: "Taah'bat's Desert Carbine",
    itemId: 242476,
    slot: EItemSlot.RANGED,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.VERS],
    specialEffect: null,
    lootSource: EDungeon.ECO,
    imgId: 'inv_-firearm_2h_outdoorethereal_c_01',
    weaponType: EWeaponType.GUN,
    mainStats: [EMainStat.AGI],
  },
  {
    name: "Soul-Scribe's Tabiqa Dagger",
    itemId: 242484,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.VERS, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.ECO,
    imgId: 'inv_knife_1h_outdoorethereal_c_01',
    weaponType: EWeaponType.DAGGER,
    mainStats: [EMainStat.INT],
  },
];
