import {
  EItemSlot,
  EMainStat,
  EOffhandType,
  ESecondaryStat,
  EWeaponType,
  TWowItem,
} from '../types/items';
import { EDungeon, ERaid, ERaidBoss } from '../types/lootSources';

export const MANUAL_ITEMS: Array<TWowItem> = [
  {
    name: "Geezle's Coercive Volt-ohmmeter",
    itemId: 234493,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.VERS],
    specialEffect: null,
    lootSource: EDungeon.FLOOD,
    imgId: 'inv_knife_1h_outdoorundermine_c_01_purple',
    weaponType: EWeaponType.DAGGER,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Sonic Ka-BOOM!-erang',
    itemId: 234491,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.HASTE],
    specialEffect: null,
    lootSource: EDungeon.FLOOD,
    imgId: 'inv_glaive_1h_outdoorundermine_c_01',
    weaponType: EWeaponType.WARGLAIVE,
    mainStats: [EMainStat.AGI],
  },
  {
    name: "Keeza's 'B.' B.B.B.F.G",
    itemId: 234492,
    slot: EItemSlot.RANGED,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.HASTE],
    specialEffect: null,
    lootSource: EDungeon.FLOOD,
    imgId: 'inv_firearm_2h_outdoorundermine_c_01',
    weaponType: EWeaponType.GUN,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Hand of Beledar',
    itemId: 221122,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.PSF,
    imgId: 'inv_mace_1h_earthendungeon_c_01',
    weaponType: EWeaponType.MACE1H,
    mainStats: [EMainStat.INT],
  },
  {
    name: "Starforged Seraph's Mace",
    itemId: 221128,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.VERS],
    specialEffect: null,
    lootSource: EDungeon.PSF,
    imgId: 'inv_mace_1h_earthendungeon_c_01',
    weaponType: EWeaponType.MACE1H,
    mainStats: [EMainStat.AGI],
  },
  {
    name: "Stoneguardian's Morningstar",
    itemId: 178834,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.HOA,
    imgId: 'inv_mace_1h_bastionquest_b_02',
    weaponType: EWeaponType.MACE1H,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Blade of Grievous Harm',
    itemId: 185824,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.HASTE],
    specialEffect: null,
    lootSource: EDungeon.STREETS,
    imgId: 'inv_sword_1h_broker2boss_d_01_blue',
    weaponType: EWeaponType.SWORD1H,
    mainStats: [EMainStat.STR],
  },
  {
    name: "Interrogator's Flensing Blade",
    itemId: 185780,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.STREETS,
    imgId: 'inv_sword_1h_broker2boss_d_01_blue',
    weaponType: EWeaponType.SWORD1H,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Fang of Alcruux',
    itemId: 185777,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.STREETS,
    imgId: 'inv_knife_1h_broker_c_01',
    weaponType: EWeaponType.DAGGER,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Gluttonous Rondel',
    itemId: 185821,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.VERS],
    specialEffect: null,
    lootSource: EDungeon.STREETS,
    imgId: 'inv_knife_1h_broker_c_01',
    weaponType: EWeaponType.DAGGER,
    mainStats: [EMainStat.INT],
  },
  {
    name: 'Yasahm the Riftbreaker',
    itemId: 185783,
    slot: EItemSlot.RANGED,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.VERS],
    specialEffect:
      'Equip: Your damaging critical strikes grant you a stack of Preternatural Charge. When you reach 5 stacks of Preternatural Charge, your next critical strike will consume all stacks to tear open a rift near your target, inflicting 29 Arcane damage.',
    lootSource: EDungeon.STREETS,
    imgId: 'inv_crossbow_2h_broker_c_01',
    weaponType: EWeaponType.CROSSBOW,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Acoustically Alluring Censer',
    itemId: 185812,
    slot: EItemSlot.OFFHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.VERS],
    specialEffect: null,
    lootSource: EDungeon.STREETS,
    imgId: 'inv_offhand_1h_broker_c_01',
    offhandType: EOffhandType.OFFHAND,
    mainStats: [EMainStat.INT],
  },
  {
    name: 'First Fist of the So Cartel',
    itemId: 185778,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.HASTE],
    specialEffect: null,
    lootSource: EDungeon.STREETS,
    imgId: 'inv_hand_1h_brokerassassin_c_01',
    weaponType: EWeaponType.FIST,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Fatebreaker, Destroyer of Futures',
    itemId: 185823,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.VERS, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.GAMBIT,
    imgId: 'inv_mace_1h_broker_c_01',
    weaponType: EWeaponType.MACE1H,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Timetwister Tulwar',
    itemId: 185841,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.VERS, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.GAMBIT,
    imgId: 'inv_sword_1h_broker_c_01',
    weaponType: EWeaponType.SWORD1H,
    mainStats: [EMainStat.INT],
  },
  {
    name: "Event Horizon's Edge",
    itemId: 185819,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.GAMBIT,
    imgId: 'inv_glaive_1h_broker_c_01',
    weaponType: EWeaponType.WARGLAIVE,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Overclocked Plexhammer',
    itemId: 237736,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.VERS],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.PLEXUS,
      raid: ERaid.MFO,
    },
    imgId: 'inv_mace_1h_etherealraid_d_01',
    weaponType: EWeaponType.MACE1H,
    mainStats: [EMainStat.INT],
  },
  {
    name: 'Factory-Issue Plexhammer',
    itemId: 237813,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.PLEXUS,
      raid: ERaid.MFO,
    },
    imgId: 'inv_mace_1h_etherealraid_d_02',
    weaponType: EWeaponType.MACE1H,
    mainStats: [EMainStat.STR],
  },
  {
    name: 'Prodigious Gene Splicer',
    itemId: 237729,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.VERS, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.LOOMITHAR,
      raid: ERaid.MFO,
    },
    imgId: 'inv_knife_1h_etherealraid_d_01',
    weaponType: EWeaponType.DAGGER,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Piercing Strandbow',
    itemId: 237732,
    slot: EItemSlot.RANGED,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.LOOMITHAR,
      raid: ERaid.MFO,
    },
    imgId: 'inv_bow_1h_etherealraid_d_01',
    weaponType: EWeaponType.BOW,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Unbound Training Claws',
    itemId: 237738,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.NAAZINDHRI,
      raid: ERaid.MFO,
    },
    imgId: 'inv_hand_1h_etherealraid_d_01',
    weaponType: EWeaponType.FIST,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Iris of the Dark Beyond',
    itemId: 237724,
    slot: EItemSlot.OFFHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.HASTE],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.ARAZ,
      raid: ERaid.MFO,
    },
    imgId: 'inv_offhand_1h_etherealraid_d_01',
    offhandType: EOffhandType.OFFHAND,
    mainStats: [EMainStat.INT],
  },
  {
    name: 'Collapsing Phaseblades',
    itemId: 237727,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.SOUL_HUNTERS,
      raid: ERaid.MFO,
    },
    imgId: 'inv_glaive_1h_etherealraid_d_01',
    weaponType: EWeaponType.WARGLAIVE,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Voidglass Kris',
    itemId: 237728,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.MASTERY],
    specialEffect:
      'Equip: Your spells have a chance to conjure voidglass shards, slicing enemies for 223218 Cosmic damage or orbiting allies to absorb 594502 damage for up to 20 sec.',
    lootSource: {
      bossName: ERaidBoss.FRACTILLUS,
      raid: ERaid.MFO,
    },
    imgId: 'inv_knife_1h_etherealraid_d_02',
    weaponType: EWeaponType.DAGGER,
    mainStats: [EMainStat.INT],
  },
  {
    name: 'Lacerated Current Caster',
    itemId: 237733,
    slot: EItemSlot.RANGED,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.HASTE],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.FRACTILLUS,
      raid: ERaid.MFO,
    },
    imgId: 'inv_crossbow_2h_etherealraid_d_01',
    weaponType: EWeaponType.CROSSBOW,
    mainStats: [EMainStat.AGI],
  },
  {
    name: "Fractillus' Last Breath",
    itemId: 237742,
    slot: EItemSlot.OFFHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.FRACTILLUS,
      raid: ERaid.MFO,
    },
    imgId: 'inv_offhand_1h_etherealraid_d_02',
    offhandType: EOffhandType.OFFHAND,
    mainStats: [EMainStat.INT],
  },
  {
    name: "Voidglass Sovereign's Blade",
    itemId: 237735,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.HASTE],
    specialEffect:
      'Equip: Your spells have a chance to conjure voidglass shards, slicing enemies for 223218 Cosmic damage or orbiting allies to absorb 594502 damage for up to 20 sec.',
    lootSource: {
      bossName: ERaidBoss.NEXUS_KING,
      raid: ERaid.MFO,
    },
    imgId: 'inv_sword_1h_etherealraid_d_01',
    weaponType: EWeaponType.SWORD1H,
    mainStats: [EMainStat.INT],
  },
  {
    name: "Oath-Breaker's Recompense",
    itemId: 237734,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.HASTE],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.NEXUS_KING,
      raid: ERaid.MFO,
    },
    imgId: 'inv_axe_1h_etherealraid_d_01',
    weaponType: EWeaponType.AXE1H,
    mainStats: [EMainStat.STR],
  },
  {
    name: 'Vengeful Netherspike',
    itemId: 237740,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.NEXUS_KING,
      raid: ERaid.MFO,
    },
    imgId: 'inv_knife_1h_etherealraid_d_02',
    weaponType: EWeaponType.DAGGER,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Ergospheric Cudgel',
    itemId: 237731,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.VERS],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.DIMENSIUS,
      raid: ERaid.MFO,
    },
    imgId: 'inv_mace_1h_etherealraid_d_02',
    weaponType: EWeaponType.MACE1H,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Nathrian Reliquary',
    itemId: 246284,
    slot: EItemSlot.OFFHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.HOA,
    imgId: 'inv_offhand_1h_oribosdungeon_c_01',
    offhandType: EOffhandType.OFFHAND,
  },
  {
    name: 'Unceremonious Bloodletter',
    itemId: 221165,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.HASTE],
    specialEffect: null,
    lootSource: EDungeon.ARA,
    imgId: 'inv_knife_1h_earthendungeon_c_01',
    weaponType: EWeaponType.DAGGER,
    mainStats: [EMainStat.INT],
  },
  {
    name: 'Arachnoid Soulcleaver',
    itemId: 221150,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.ARA,
    imgId: 'inv_sword_1h_earthendungeon_c_02',
    weaponType: EWeaponType.SWORD1H,
    mainStats: [EMainStat.INT],
  },
  {
    name: "Parson's Ornamented Blade",
    itemId: 221138,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.VERS, ESecondaryStat.CRIT],
    specialEffect: null,
    lootSource: EDungeon.DAWN,
    imgId: 'inv_knife_1h_earthendungeon_c_02',
    weaponType: EWeaponType.DAGGER,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Overflowing Umbral Pail',
    itemId: 221132,
    slot: EItemSlot.OFFHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.VERS],
    specialEffect: null,
    lootSource: EDungeon.DAWN,
    imgId: 'inv_offhand_1h_earthendungeon_c_01',
    offhandType: EOffhandType.OFFHAND,
  },
  {
    name: "Shipwrecker's Bludgeon",
    itemId: 221145,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.HASTE],
    specialEffect: null,
    lootSource: EDungeon.DAWN,
    imgId: 'inv_mace_1h_earthendungeon_c_01',
    weaponType: EWeaponType.MACE1H,
    mainStats: [EMainStat.STR],
  },
  {
    name: 'Zephyrous Sail Carver',
    itemId: 221144,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.VERS],
    specialEffect: null,
    lootSource: EDungeon.DAWN,
    imgId: 'inv_sword_1h_earthendungeon_c_02',
    weaponType: EWeaponType.SWORD1H,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Recurved Hull Impaler',
    itemId: 221143,
    slot: EItemSlot.RANGED,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.DAWN,
    imgId: 'inv_crossbow_2h_earthendungeon_c_01',
    weaponType: EWeaponType.CROSSBOW,
    mainStats: [EMainStat.AGI],
  },
  {
    name: "Swarmite's Frenzied Pedicel",
    itemId: 242464,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.ECO,
    imgId: 'inv_wand_1h_outdoorethereal_c_01',
    weaponType: EWeaponType.WAND,
    mainStats: [EMainStat.INT],
  },
  {
    name: 'Mandibular Bonewhacker',
    itemId: 242470,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.VERS],
    specialEffect: null,
    lootSource: EDungeon.ECO,
    imgId: 'inv_mace_1h_outdoorethereal_c_02',
    weaponType: EWeaponType.MACE1H,
    mainStats: [EMainStat.STR],
  },
  {
    name: "Taah'bat's Desert Carbine",
    itemId: 242476,
    slot: EItemSlot.RANGED,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.VERS],
    specialEffect: null,
    lootSource: EDungeon.ECO,
    imgId: 'inv_-firearm_2h_outdoorethereal_c_01',
    weaponType: EWeaponType.GUN,
    mainStats: [EMainStat.AGI],
  },
  {
    name: "Soul-Scribe's Tabiqa Dagger",
    itemId: 242484,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.VERS, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.ECO,
    imgId: 'inv_knife_1h_outdoorethereal_c_01',
    weaponType: EWeaponType.DAGGER,
    mainStats: [EMainStat.INT],
  },
  {
    name: 'Resolute Runeglaive',
    itemId: 251106,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.VERS, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.MT,
    imgId: 'inv_glaive_1h_bloodelfguard_d_01',
    weaponType: EWeaponType.WARGLAIVE,
    mainStats: [EMainStat.AGI, EMainStat.INT],
  },
  {
    name: 'Splitshroud Stinger',
    itemId: 251111,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.HASTE],
    specialEffect: null,
    lootSource: EDungeon.MT,
    imgId: 'inv_knife_1h_dungeonharronir_c_02',
    weaponType: EWeaponType.DAGGER,
    mainStats: [EMainStat.INT],
  },
  {
    name: 'Shadowslash Slicer',
    itemId: 251122,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.MT,
    imgId: 'inv_sword_1h_domanaar_b_01',
    weaponType: EWeaponType.SWORD1H,
    mainStats: [EMainStat.AGI],
  },
  {
    name: "Defiant Defender's Drape",
    itemId: 260312,
    slot: EItemSlot.BACK,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.HASTE],
    specialEffect: null,
    lootSource: EDungeon.MT,
    imgId: 'inv_cape_plate_dungeonharronir_c_01',
  },
  {
    name: 'Ceremonial Hexblade',
    itemId: 251178,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.HASTE],
    specialEffect: null,
    lootSource: EDungeon.MC,
    imgId: 'inv_knife_1h_dungeonharronir_c_02',
    weaponType: EWeaponType.DAGGER,
    mainStats: [EMainStat.INT],
  },
  {
    name: 'Soulblight Cleaver',
    itemId: 251175,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.MC,
    imgId: 'inv_axe_1h_amani_b_01',
    weaponType: EWeaponType.AXE1H,
    mainStats: [EMainStat.AGI],
  },
  {
    name: "Deceiver's Rotbow",
    itemId: 251174,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.MC,
    imgId: 'inv_bow_1h_amani_c_01',
    weaponType: EWeaponType.BOW,
    mainStats: [EMainStat.AGI],
  },
  {
    name: "Berserker's Hexclaws",
    itemId: 251163,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.VERS],
    specialEffect: null,
    lootSource: EDungeon.MC,
    imgId: 'inv_hand_1h_dungeonharronir_c_02',
    weaponType: EWeaponType.FIST,
    mainStats: [EMainStat.INT],
  },
  {
    name: "Soulhunter's Mask",
    itemId: 251161,
    slot: EItemSlot.BACK,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.VERS],
    specialEffect: null,
    lootSource: EDungeon.MC,
    imgId: 'inv_cape_special_hextroll_d_01',
  },
  {
    name: 'Dreadflail Bludgeon',
    itemId: 251207,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.VERS],
    specialEffect: null,
    lootSource: EDungeon.NPX,
    imgId: 'inv_mace_1h_arathoroutdoor_d_01',
    weaponType: EWeaponType.MACE1H,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Radiant Slicer',
    itemId: 251212,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.VERS],
    specialEffect: null,
    lootSource: EDungeon.NPX,
    imgId: 'inv_knife_1h_dungeonharronir_c_01',
    weaponType: EWeaponType.DAGGER,
    mainStats: [EMainStat.AGI],
  },
  {
    name: "Hurricane's Heart",
    itemId: 251095,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.HASTE],
    specialEffect: null,
    lootSource: EDungeon.WS,
    imgId: 'inv_bow_1h_dungeonharronir_c_01',
    weaponType: EWeaponType.BOW,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Sigil of the Restless Heart',
    itemId: 251094,
    slot: EItemSlot.OFFHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.VERS],
    specialEffect: null,
    lootSource: EDungeon.WS,
    imgId: 'inv_offhand_1h_dungeonharronir_c_01',
    offhandType: EOffhandType.OFFHAND,
    mainStats: [EMainStat.INT],
  },
  {
    name: 'Warworn Cleaver',
    itemId: 251088,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.VERS],
    specialEffect: null,
    lootSource: EDungeon.WS,
    imgId: 'inv_axe_1h_dungeonharronir_c_01',
    weaponType: EWeaponType.AXE1H,
    mainStats: [EMainStat.STR],
  },
  {
    name: 'Excavating Cudgel',
    itemId: 251083,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.WS,
    imgId: 'inv_mace_1h_dungeonharronir_c_02',
    weaponType: EWeaponType.MACE1H,
    mainStats: [EMainStat.INT],
  },
  {
    name: 'Spellbane Cutlass',
    itemId: 193711,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.VERS],
    specialEffect: null,
    lootSource: EDungeon.AA,
    imgId: 'inv_sword_1h_drakonid_c_01',
    weaponType: EWeaponType.SWORD1H,
    mainStats: [EMainStat.STR],
  },
  {
    name: "Mystakria's Harvester",
    itemId: 193717,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.VERS],
    specialEffect: null,
    lootSource: EDungeon.AA,
    imgId: 'inv_glaive_1h_drakonid_c_01',
    weaponType: EWeaponType.WARGLAIVE,
    mainStats: [EMainStat.AGI, EMainStat.INT],
  },
  {
    name: 'Spellboon Saber',
    itemId: 193710,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.AA,
    imgId: 'inv_sword_1h_dragon_c_01',
    weaponType: EWeaponType.SWORD1H,
    mainStats: [EMainStat.INT],
  },
  {
    name: "Vexamus' Expulsion Rod",
    itemId: 193709,
    slot: EItemSlot.OFFHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.HASTE],
    specialEffect: null,
    lootSource: EDungeon.AA,
    imgId: 'inv_offhand_1h_drakonid_c_01',
    offhandType: EOffhandType.OFFHAND,
    mainStats: [EMainStat.INT],
  },
  {
    name: 'Potion-Stained Cloak',
    itemId: 193712,
    slot: EItemSlot.BACK,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.VERS],
    specialEffect: null,
    lootSource: EDungeon.AA,
    imgId: 'inv_leather_dragondungeon_c_01_cape',
  },
  {
    name: "Surgeon's Needle",
    itemId: 50227,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.VERS],
    specialEffect: null,
    lootSource: EDungeon.POS,
    imgId: 'inv_weapon_shortblade_100',
    weaponType: EWeaponType.DAGGER,
    mainStats: [EMainStat.INT],
  },
  {
    name: "Krick's Beetle Stabber",
    itemId: 49807,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.HASTE],
    specialEffect: null,
    lootSource: EDungeon.POS,
    imgId: 'inv_weapon_shortblade_80',
    weaponType: EWeaponType.DAGGER,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Rimebane Rifle',
    itemId: 49813,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.POS,
    imgId: 'inv_weapon_rifle_13',
    weaponType: EWeaponType.GUN,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Cloak of the Fallen Cardinal',
    itemId: 49823,
    slot: EItemSlot.BACK,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.VERS],
    specialEffect: null,
    lootSource: EDungeon.POS,
    imgId: 'inv_misc_cape_18',
  },
  {
    name: 'Scepter of the Endless Night',
    itemId: 258525,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.HASTE],
    specialEffect: null,
    lootSource: EDungeon.SEAT,
    imgId: 'inv_mace_1h_cataclysm_c_01',
    weaponType: EWeaponType.MACE1H,
    mainStats: [EMainStat.INT],
  },
  {
    name: 'Grips of the Dark Viceroy',
    itemId: 258524,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.VERS, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.SEAT,
    imgId: 'inv_hand_1h_draenorhonor_c_01',
    weaponType: EWeaponType.FIST,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Blazing Sunclaws',
    itemId: 258438,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.SR,
    imgId: 'inv_hand_1h_draenordungeon_c_01',
    weaponType: EWeaponType.FIST,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Arcanic of the High Sage',
    itemId: 258050,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.CRIT],
    specialEffect: null,
    lootSource: EDungeon.SR,
    imgId: 'inv_hand_1h_draenordungeon_c_02',
    weaponType: EWeaponType.FIST,
    mainStats: [EMainStat.INT],
  },
  {
    name: 'Edge of the Burning Sun',
    itemId: 258436,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.SR,
    imgId: 'inv_knife_1h_draenordungeon_c_01',
    weaponType: EWeaponType.DAGGER,
    mainStats: [EMainStat.AGI],
  },
  {
    name: "Stormshaper's Crossbow",
    itemId: 258412,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.VERS, ESecondaryStat.CRIT],
    specialEffect: null,
    lootSource: EDungeon.SR,
    imgId: 'inv_bow_2h_crossbow_draenordungeon_c_01',
    weaponType: EWeaponType.BOW,
    mainStats: [EMainStat.AGI],
  },
  {
    name: "Rukhran's Solar Reliquary",
    itemId: 258472,
    slot: EItemSlot.OFFHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.SR,
    offhandType: EOffhandType.OFFHAND,
    imgId: 'inv_offhand_1h_raidmidnight_d_01',
  },
  {
    name: 'Grips of the Dark Viceroy',
    itemId: 258412,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.VERS, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.SEAT,
    imgId: 'inv_hand_1h_draenorhonor_c_01',
    weaponType: EWeaponType.FIST,
    mainStats: [EMainStat.AGI],
  },
  {
    name: "Wand of Saprish's Gaze",
    itemId: 258516,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.VERS, ESecondaryStat.CRIT],
    specialEffect: null,
    lootSource: EDungeon.SEAT,
    imgId: 'inv_wand_1h_draenordungeon_c_01',
    weaponType: EWeaponType.WAND,
    mainStats: [EMainStat.INT],
  },
  {
    name: "Nezhar's Netherclaw",
    itemId: 258523,
    slot: EItemSlot.OFFHAND,
    secondaryStats: [ESecondaryStat.MASTERY, ESecondaryStat.CRIT],
    specialEffect: null,
    lootSource: EDungeon.SEAT,
    imgId: 'inv_offhand_1h_ardenwealdquest_b_01',
    offhandType: EOffhandType.OFFHAND,
  },
  {
    name: "Skybreaker's Blade",
    itemId: 258218,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.MASTERY, ESecondaryStat.CRIT],
    specialEffect: null,
    lootSource: EDungeon.SR,
    imgId: 'inv_sword_1h_short_c_03',
    weaponType: EWeaponType.SWORD1H,
    mainStats: [EMainStat.INT],
  },
  {
    name: 'Beakbreaker Scimitar',
    itemId: 258048,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.VERS, ESecondaryStat.CRIT],
    specialEffect: null,
    lootSource: EDungeon.SR,
    imgId: 'inv_sword_1h_draenordungeon_c_01',
    weaponType: EWeaponType.SWORD1H,
    mainStats: [EMainStat.STR],
  },
  {
    name: "Clutchmates' Caress",
    itemId: 249287,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.VAELGOR,
      raid: ERaid.VS,
    },
    imgId: 'inv_mace_1h_raidmidnight_d_01',
    weaponType: EWeaponType.MACE1H,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Emblazoned Sunglaive',
    itemId: 249280,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.VAELGOR,
      raid: ERaid.VS,
    },
    imgId: 'inv_glaive_1h_raidmidnight_d_01',
    weaponType: EWeaponType.WARGLAIVE,
    mainStats: [EMainStat.AGI, EMainStat.INT],
  },
  {
    name: 'Blade of the Blind Verdict',
    itemId: 249294,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.LIGHT_VANGUARD,
      raid: ERaid.VS,
    },
    imgId: 'inv_sword_1h_raidmidnight_d_01',
    weaponType: EWeaponType.SWORD1H,
    mainStats: [EMainStat.INT],
  },
  {
    name: "Arator's Swift Remembrance",
    itemId: 260423,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.CRIT],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.CROWN_COSMOS,
      raid: ERaid.VS,
    },
    imgId: 'inv_sword_1h_raidmidnight_d_01',
    weaponType: EWeaponType.SWORD1H,
    mainStats: [EMainStat.AGI],
  },
  {
    name: "Turalyon's False Echo",
    itemId: 249295,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.CRIT],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.CROWN_COSMOS,
      raid: ERaid.VS,
    },
    imgId: 'inv_mace_1h_raidmidnight_d_01',
    weaponType: EWeaponType.MACE1H,
    mainStats: [EMainStat.STR],
  },
  {
    name: "Ranger-Captain's Lethal Recurve",
    itemId: 249288,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.CRIT],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.CROWN_COSMOS,
      raid: ERaid.VS,
    },
    imgId: 'inv_bow_1h_raidmidnight_d_01',
    weaponType: EWeaponType.BOW,
    mainStats: [EMainStat.AGI],
  },
  {
    name: "Belo'ren's Swift Talon",
    itemId: 249284,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.MASTERY, ESecondaryStat.CRIT],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.BELOREN,
      raid: ERaid.VS,
    },
    imgId: 'inv_knife_1h_raidmidnight_d_01',
    weaponType: EWeaponType.DAGGER,
    mainStats: [EMainStat.AGI],
  },
  {
    name: "Belo'melorn, the Shattered Talon",
    itemId: 249283,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.MASTERY, ESecondaryStat.HASTE],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.BELOREN,
      raid: ERaid.VS,
    },
    imgId: 'inv_knife_1h_raidmidnight_d_01',
    weaponType: EWeaponType.DAGGER,
    mainStats: [EMainStat.INT],
  },
  {
    name: 'Lightless Lament',
    itemId: 260408,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT],
    specialEffect:
      "Dealing damage has a high chance to unleash a Heaven's Glaive, dealing 57 Cosmic damage split between nearby enemies. Damage increased by 30% per additional enemy, up to 150%",
    lootSource: EDungeon.SEAT,
    imgId: 'inv_glaive_1h_darknaaru_d_01',
    weaponType: EWeaponType.WARGLAIVE,
    mainStats: [EMainStat.INT, EMainStat.AGI],
  },
  {
    name: 'Hungering Victory',
    itemId: 249925,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.MASTERY, ESecondaryStat.VERS],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.VORASIUS,
      raid: ERaid.VS,
    },
    imgId: 'inv_knife_1h_raidmidnight_d_02',
    weaponType: EWeaponType.DAGGER,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Grimoire of the Eternal Light',
    itemId: 249276,
    slot: EItemSlot.OFFHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.HASTE],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.VORASIUS,
      raid: ERaid.VS,
    },
    imgId: 'inv_offhand_1h_raidmidnight_d_01',
    offhandType: EOffhandType.OFFHAND,
    mainStats: [EMainStat.INT],
  },
  {
    name: 'Blade of the Final Twilight',
    itemId: 249281,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.MASTERY, ESecondaryStat.CRIT],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.FALLEN_SALHADAAR,
      raid: ERaid.VS,
    },
    imgId: 'inv_sword_1h_raidmidnight_d_01',
    weaponType: EWeaponType.SWORD1H,
    mainStats: [EMainStat.STR],
  },
  {
    name: "Tormentor's Bladed Fists",
    itemId: 249298,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.VERS],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.FALLEN_SALHADAAR,
      raid: ERaid.VS,
    },
    imgId: 'inv_hand_1h_raidmidnight_d_01',
    weaponType: EWeaponType.FIST,
    mainStats: [EMainStat.AGI],
  },
  {
    name: 'Draconic Nullcape',
    itemId: 249370,
    slot: EItemSlot.BACK,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.VAELGOR,
      raid: ERaid.VS,
    },
    imgId: 'inv_cape_plate_raidpaladinmidnight_d_01',
  },
  {
    name: 'Rigid Scale Greatcloak',
    itemId: 258575,
    slot: EItemSlot.BACK,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: EDungeon.SR,
    imgId: 'inv_cape_draenordungeon_c_02_plate',
  },
  {
    name: 'Tome of Alnscorned Regret',
    itemId: 249922,
    slot: EItemSlot.OFFHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.CHIMAERUS,
      raid: ERaid.DR,
    },
    offhandType: EOffhandType.OFFHAND,
    imgId: 'inv_offhand_1h_raidmidnight_d_01',
  },
  {
    name: 'Weight of Command',
    itemId: 249293,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.VERS],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.AVERZIAN,
      raid: ERaid.DR,
    },
    weaponType: EWeaponType.MACE1H,
    imgId: 'inv_mace_1h_raidmidnight_d_02',
    mainStats: [EMainStat.INT],
  },
  {
    name: "Imperator's Banner",
    itemId: 249335,
    slot: EItemSlot.BACK,
    secondaryStats: [ESecondaryStat.CRIT, ESecondaryStat.VERS],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.AVERZIAN,
      raid: ERaid.DR,
    },
    imgId: 'inv_plate_raiddeathknightmidnight_d_01_cape',
  },
  {
    name: 'Sunstrike Rifle',
    itemId: 249279,
    slot: EItemSlot.MAINHAND,
    secondaryStats: [ESecondaryStat.HASTE, ESecondaryStat.MASTERY],
    specialEffect: null,
    lootSource: {
      bossName: ERaidBoss.AVERZIAN,
      raid: ERaid.VS,
    },
    imgId: 'inv_firearm_2h_raidmidnight_d_01',
    weaponType: EWeaponType.GUN,
    mainStats: [EMainStat.AGI],
  },
];
